apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wg-reverse-proxy-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ineb01/wg-reverse-proxy.git  # Replace with your actual repo
    targetRevision: HEAD
    path: manifests  # Update this if your manifests are in a different path
  destination:
    server: https://kubernetes.default.svc
    namespace: wg-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
